python: '3.10'
# Use uv pip for speedup, but fallback to classic pip if we fail
# Upgrade pip to avoid https://stackoverflow.com/a/73779542/
install: 'uv pip install pwntools ipython pycryptodome mpmath sympy ruff'
